### ISSUE TITLE
Examples need minor updates

### ISSUE THREAD

**Issue by MartyMacGyver** [lincomatic/LiquidTWI2#11]
The examples included are somewhat out of date and could use some minor rework to be compatible with typical boards.

Update to the .ino format (is anyone expecting to use this library with a pre-1.0 IDE?)

The comments in both examples mention the pins to wire up, but that varies by board... per http://arduino.cc/en/Reference/Wire:

```
  Board      I2C / TWI pins
  ---------  --------------------------
  Uno, Yun   A4 (SDA), A5 (SCL)
  Mega2560   20 (SDA), 21 (SCL)
  Leonardo    2 (SDA),  3 (SCL)
  Due        20 (SDA), 21 (SCL)
```
(Purposely omitting SDA1/SCL1 on the Due because they are non-trivial to use IMHO)

Also, the default address would be better to be something like 0x20 (which is a typical default base address.

**Comment by nsayer** [comment]
Don't forget too that you can use the library with TinyWireM on ATTiny variants. Given that, I think it's better to just drop the pin list entirely, since there's no chance of it being kept up-to-date and complete.

**Comment by MartyMacGyver** [comment]
I'm open to either updating it or removing it - currently it's just confusingly vague.

**Comment by lincomatic** [comment]
I may be in the minority, but I still use 0022. The output of 1.0+ is bloated. OK, I'll update the samples.

**Comment by lincomatic** [comment]
BTW, the address 0 works w/ the Adafruit board that I used for the example, so I don't see why it should be changed. Or does it work w/ 0x20 w/ that board as well?

**Comment by MartyMacGyver** [comment]
I didn't know 0022 was still in active use. Well, then perhaps not updating those files to .ino is just as well.

As for the address, the backpacks I've used have been in the 0x20-0x27 range (one being the http://www.adafruit.com/product/292 which may be the same one you have).

I just ran a little test and actually 0x20 and 0x00 appear to work equally well which was confusing - but a run of the I2C scanner reminded me that 0x00-0x02 are not to be used for addressing (per http://www.i2c-bus.org/addressing/). So yes, I think it ought to be set to 0x20 because that's a valid I2C address and is the default for the common backpacks.

**Comment by lincomatic** [comment]
OK, I'll change the code to use 0x20. And I'll add the common pinouts, as you suggested. But as Nick said, there are a lot of variants out there... these are just examples, and the user needs to figure out how hook up their own devices and what I2C address to use. I've just duplicated the PDE's as INO's. But frankly, if someone can't figure that out, they probably won't be able figure out how to use the library.

**Comment by MartyMacGyver** [comment]
The pinouts are handy but again I'm fine with leaving them out too (a notation that says this uses the regular I2C pins for your device is perhaps enough - the only thing I had problems with was the fact they (in the original Adafruit code) just assumed you were using an Uno - made hooking things up today rather triky).

For all that, I do appreciate the library! It's working well, which is far more than I can say for other ones I tried today.
