### ISSUE TITLE
Add bridge to setClock in Wire for easy change of TWI frequency

### ISSUE THREAD

**Issue by justmyopinion** [lincomatic/LiquidTWI2#12]
Would it be possible to add this function to TWI2, so it could be called like this in code LCD.setClock(100000)?

void LiquidTWI2::setClock(uint32_t frequ) {
  Wire.setClock(frequ);
}

**Comment by lincomatic** [comment]
Setting the clock in Wire will have a global effect, not just local to LiquidTWI2.. therefore, I don't think it's a good idea.
