### ISSUE TITLE
Row Offset for 16x4 lcd is wrong

### ISSUE THREAD

**Issue by TilTisback** [lincomatic/LiquidTWI2#15]
Hello,

the row offset in "LiquidTWI2.cpp" line 347 is wrong.
https://github.com/lincomatic/LiquidTWI2/blob/30aa480782053c7ffd301031e8809a98a2eb063f/LiquidTWI2.cpp#L347

when you compile it with a 16x4 LCD you get this: (im just filling all the characters with 0-15 in hex)
![photo_2019-06-23_22-40-32](https://user-images.githubusercontent.com/13772017/59981709-f7edb900-9607-11e9-8774-910d71e8af5d.jpg)

when you change the row offset to 
`int row_offsets[] = { 0x00, 0x40, 0x10, 0x50 };`
you get this like expected:
![photo_2019-06-23_22-40-38](https://user-images.githubusercontent.com/13772017/59981732-2e2b3880-9608-11e9-93b0-541a10416f32.jpg)

i think noone has found this bug yet, because i am using a 16x4 LCD instead of a 16x2 LCD.

**Comment by lincomatic** [comment]
Thank you.

https://github.com/lincomatic/LiquidTWI2/commit/070881fa5c31fb6d76ff71a5e80428b4b58ce28a

**Comment by FixyNeko** [comment]
this fix is wrong, it only transfer the problem that was on the 16x4 screen to the 20x4 ones. There should be 2 distinct offset based on the width of the lcd
